// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendasSolutto.Data;

namespace VendasSolutto.Migrations
{
    [DbContext(typeof(VendasSoluttoContext))]
    [Migration("20220820000200_Produtos")]
    partial class Produtos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VendasSolutto.Models.Produtos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("produto_nome")
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("valor_unitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("VendasSolutto.Models.Vendas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cliente_cnpj")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("data_venda")
                        .HasColumnType("datetime");

                    b.Property<int>("quantidade_pagamentos")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
