// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendasSolutto.Data;

namespace VendasSolutto.Migrations
{
    [DbContext(typeof(VendasSoluttoContext))]
    partial class VendasSoluttoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VendasSolutto.Models.ItensVenda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("produtoid")
                        .HasColumnType("int");

                    b.Property<decimal>("quantidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("vendaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("produtoid");

                    b.HasIndex("vendaid");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("VendasSolutto.Models.Pagamentos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("data_pagamento")
                        .HasColumnType("date");

                    b.Property<DateTime>("data_vencimento")
                        .HasColumnType("date");

                    b.Property<string>("descricao_pagamento")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("valor_pago")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("vendasid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("vendasid");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("VendasSolutto.Models.Produtos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("produto_nome")
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("valor_unitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("VendasSolutto.Models.RetornoRelatorioBarra", b =>
                {
                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("total_dia")
                        .HasColumnType("double");

                    b.HasKey("data");

                    b.ToTable("retornoBarra");
                });

            modelBuilder.Entity("VendasSolutto.Models.RetornoRelatorioPizza", b =>
                {
                    b.Property<string>("produto_nome")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<double>("valor_vendido")
                        .HasColumnType("double");

                    b.HasKey("produto_nome");

                    b.ToTable("retornoPizza");
                });

            modelBuilder.Entity("VendasSolutto.Models.Vendas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cliente_cnpj")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("data_venda")
                        .HasColumnType("datetime");

                    b.Property<int>("quantidade_pagamentos")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("VendasSolutto.Models.ItensVenda", b =>
                {
                    b.HasOne("VendasSolutto.Models.Produtos", "produto")
                        .WithMany()
                        .HasForeignKey("produtoid");

                    b.HasOne("VendasSolutto.Models.Vendas", "venda")
                        .WithMany()
                        .HasForeignKey("vendaid");
                });

            modelBuilder.Entity("VendasSolutto.Models.Pagamentos", b =>
                {
                    b.HasOne("VendasSolutto.Models.Vendas", "vendas")
                        .WithMany()
                        .HasForeignKey("vendasid");
                });
#pragma warning restore 612, 618
        }
    }
}
